build:
    tests:
        override:
            -
                command: phpunit
                coverage:
                    file: reports/phpunit.coverage.xml
                    format: php-clover